### ISSUE TITLE
Add Support for DNN 10.0

### ISSUE THREAD

**Issue by BeniFreitag** [2sic/dnn-theme-2shine-bs5#19]
2shine Version 5.3.6 doesn't work with DNN 10.0.0.

**Error:**
Could Not Load Theme: /Portals/_default/skins/2shinebs5/default.ascx, Error: ...\Portals\_default\skins\2shinebs5\controls\theme-body.ascx(16): error CS0117: 'PortalController' does not contain a definition for 'GetCurrentPortalSettings'

**Comment by crash2000** [comment]
I have also found this issue with 10.0.0

**Comment by jeremy-farrance** [comment]
I just ran into this too, thanks in advance for the next update or patch!

**Comment by ropalko** [comment]
Hello everyone.

For a quickfix change `PortalController.GetCurrentPortalSettings()` to `PortalSettings`

For example `PortalController.GetCurrentPortalSettings().HomeTabId` to `PortalSettings.HomeTabId`

**Comment by enfJoao** [comment]
+1 For this request.

**Comment by ropalko** [comment]
fixed in new release
